title: Tabelca
email: website@tabelca.com
description: Compare products and services in tabular data.
baseurl: ""
url: ""
markdown: kramdown
plugins:
  - jekyll-feed
collections:
  products:
    output: true
exclude:
   - .idea/
   - Gemfile
   - Gemfile.lock
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
